language: generic
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_1d8c94bea0f3_key -iv $encrypted_1d8c94bea0f3_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod +x dev/bootstrap.sh
script:
- "./dev/bootstrap.sh"
- docker-compose -f docker-compose.dev.yml up -d
- docker-compose -f docker-compose.dev.yml exec -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN plantit coverage run --source='.' ./manage.py test
- docker-compose -f docker-compose.dev.yml exec -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN plantit coveralls
deploy:
- provider: script
  script: bash dev/deploy-ssh.sh
  on:
    branch: master
