# Runs PlantIT in production mode.
#
# See README for information and usage.

version: '3.7'

services:

  plantit:
    command: ["gunicorn", "--bind", ":8000", "--log-level", "debug", "plantit.wsgi:application"]
    networks:
      - ngnix_network
      - default
    restart: always
    healthcheck:
      test: curl -f http://localhost:8000/ping/
      interval: 20s
      timeout: 20s
      retries: 2
      start_period: 20s
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "plantit"

  postgres:
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "postgres"

  adminer:
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "adminer"

  rabbitmq:
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "rabbitmq"

  celery:
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "celery"

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/ssl/:/opt/plantit/config/ssl/
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/letsencrypt/:/etc/letsencrypt/
      - ./plantit/static/:/opt/plantit/static/:ro
      - ./plantit/files/public/:/opt/plantit/public/:ro
    depends_on:
      - plantit
    networks:
      - ngnix_network
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "ngnix"

networks:
  ngnix_network:
    driver: bridge

volumes:
  pgdata:
