version: '3.7'
services:
  plantit:
    image: computationalplantscience/plantit
    working_dir: /code/plantit
    depends_on:
      - celery
      - sandbox
    volumes:
      - .:/code
    environment:
      - VUE_APP_TITLE=${VUE_APP_TITLE}
      - CYVERSE_REDIRECT_URL=${CYVERSE_REDIRECT_URL}
      - CYVERSE_CLIENT_ID=${CYVERSE_CLIENT_ID}
      - CYVERSE_CLIENT_SECRET=${CYVERSE_CLIENT_SECRET}
      - NODE_ENV=${NODE_ENV}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_FIELD_ENCRYPTION_KEY=${DJANGO_FIELD_ENCRYPTION_KEY}
      - DJANGO_API_URL=${DJANGO_API_URL}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_ADMIN_USERNAME=${DJANGO_ADMIN_USERNAME}
      - DJANGO_ADMIN_PASSWORD=${DJANGO_ADMIN_PASSWORD}
      - DJANGO_SECURE_SSL_REDIRECT=${DJANGO_SECURE_SSL_REDIRECT}
      - DJANGO_SESSION_COOKIE_SECURE=${DJANGO_SESSION_COOKIE_SECURE}
      - DJANGO_CSRF_COOKIE_SECURE=${DJANGO_CSRF_COOKIE_SECURE}
      - SQL_ENGINE=${SQL_ENGINE}
      - GITHUB_AUTH_URI=${GITHUB_AUTH_URI}
      - GITHUB_REDIRECT_URI=${GITHUB_REDIRECT_URI}
      - GITHUB_KEY=${GITHUB_KEY}
      - GITHUB_SECRET=${GITHUB_SECRET}
    command: ["gunicorn", "--bind", ":8000", "--log-level", "debug", "plantit.wsgi:application"]
    networks:
      - ngnix_network
      - default
    restart: always
    healthcheck:
      test: curl -f http://localhost:8000/ping/
      interval: 20s
      timeout: 20s
      retries: 2
      start_period: 20s
  celery:
    image: computationalplantscience/plantit
    command: ["celery", "-A", "plantit", "worker", "--loglevel=info"]
    volumes:
      - .:/code
    working_dir: /code/plantit
    depends_on:
      - rabbitmq
    environment:
      - CYVERSE_REDIRECT_URL=${CYVERSE_REDIRECT_URL}
      - CYVERSE_CLIENT_ID=${CYVERSE_CLIENT_ID}
      - CYVERSE_CLIENT_SECRET=${CYVERSE_CLIENT_SECRET}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_FIELD_ENCRYPTION_KEY=${DJANGO_FIELD_ENCRYPTION_KEY}
      - DJANGO_API_URL=${DJANGO_API_URL}
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=${DJANGO_SECURE_SSL_REDIRECT}
      - DJANGO_SESSION_COOKIE_SECURE=${DJANGO_SESSION_COOKIE_SECURE}
      - DJANGO_CSRF_COOKIE_SECURE=${DJANGO_CSRF_COOKIE_SECURE}
      - SQL_ENGINE=${SQL_ENGINE}
      - GITHUB_AUTH_URI=${GITHUB_AUTH_URI}
      - GITHUB_REDIRECT_URI=${GITHUB_REDIRECT_URI}
      - GITHUB_KEY=${GITHUB_KEY}
      - GITHUB_SECRET=${GITHUB_SECRET}
    healthcheck:
      test: celery -A plantit status | grep "OK"
      interval: 60s
      timeout: 60s
      retries: 2
      start_period: 20s
    restart: always
  rabbitmq:
    image: rabbitmq:3.7.6-management
    hostname: rabbitmq
    ports:
      - 15672:15672
    healthcheck:
      test: python -c "import urllib2; print urllib2.urlopen('http://localhost:15672').getcode();" | grep "200"
      interval: 60s
      timeout: 60s
      retries: 2
      start_period: 20s
    restart: always
  sandbox:
    image: computationalplantscience/plantit-sandbox
    working_dir: /opt/plantit-cli-home
    privileged: true
    restart: always
    volumes:
      - ./sandbox/:/test/
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/ssl/:/opt/plantit/config/ssl/
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/certbot/conf:/etc/letsencrypt/
      - ./config/certbot/www:/var/www/certbot
      - ./plantit/static/:/opt/plantit/static/:ro
      - ./plantit/files/public/:/opt/plantit/public/:ro
    depends_on:
      - plantit
    networks:
      - ngnix_network
    restart: always
  certbot:
    image: certbot/certbot
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt/
      - ./config/certbot/www:/var/www/certbot
networks:
  ngnix_network:
    driver: bridge
