# Runs `DIRT2_Webplatform` in production mode.
#
# See README for information and usage.

version: '3.7'

services:

  plantit:
    command: ["gunicorn", "--bind", ":8000", "--log-level", "debug", "plantit.wsgi:application"]
    networks:
      - ngnix_network
      - default
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "plantit"

  postgres:
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "postgres"

  adminer:
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "adminer"

  rabbitmq:
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "rabbitmq"

  celery:
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "celery"

  flower:
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "flower"

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./plantit/static/:/opt/plantit/static/:ro
      - ./plantit/files/public/:/opt/plantit/public/:ro
    depends_on:
      - plantit
    networks:
      - ngnix_network
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "ngnix"

networks:
  ngnix_network:
    driver: bridge