version: '3.7'
services:
  plantit:
    command: ["python", "manage.py", "runserver", "0.0.0.0:80"]
    depends_on:
      - sandbox
      - irods
    ports:
      - "80:80"
    healthcheck:
      test: curl -f http://localhost:80/ping/
      interval: 20s
      timeout: 20s
      retries: 2
      start_period: 20s
  irods:
    image: mjstealey/irods-provider-postgres:4.2.3