# Runs PlantIT in production mode.
#
# See README for information and usage.

version: '3.7'

services:

  plantit:
    command: ["gunicorn", "--bind", ":8000", "--log-level", "debug", "plantit.wsgi:application"]
    networks:
      - ngnix_network
      - default
      - plantit-logging_graylog
    restart: always
    healthcheck:
      test: curl -f http://localhost:8000/ping/
      interval: 20s
      timeout: 20s
      retries: 2
      start_period: 20s
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "plantit"

  postgres:
    networks:
      - plantit-logging_graylog
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "postgres"

  adminer:
    networks:
      - plantit-logging_graylog
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "adminer"

  rabbitmq:
    networks:
      - plantit-logging_graylog
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "rabbitmq"

  # celery:
  #   logging:
  #     driver: gelf
  #     options:
  #       gelf-address: ${GRAYLOG_GELF_URI}
  #       tag: "celery"

  dagster-celery:
    networks:
      - plantit-logging_graylog
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "dagster-celery"

  dagit:
    networks:
      - plantit-logging_graylog
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "dagit"

  flower:
    networks:
      - plantit-logging_graylog
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "flower"

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./plantit/static/:/opt/plantit/static/:ro
      - ./plantit/files/public/:/opt/plantit/public/:ro
    depends_on:
      - plantit
    networks:
      - ngnix_network
      - plantit-logging_graylog
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: ${GRAYLOG_GELF_URI}
        tag: "ngnix"

networks:
  ngnix_network:
    driver: bridge
  plantit-logging_graylog:
    driver: bridge