version: '3.7'
services:
  plantit:
    image: computationalplantscience/plantit
    working_dir: /code/plantit
    depends_on:
      - celery
      - sandbox
    volumes:
      - .:/code
    environment:
      - VUE_APP_TITLE=${VUE_APP_TITLE}
      - CYVERSE_REDIRECT_URL=${CYVERSE_REDIRECT_URL}
      - CYVERSE_CLIENT_ID=${CYVERSE_CLIENT_ID}
      - CYVERSE_CLIENT_SECRET=${CYVERSE_CLIENT_SECRET}
      - CYVERSE_TOKEN_REFRESH_MINUTES=${CYVERSE_TOKEN_REFRESH_MINUTES}
      - NODE_ENV=${NODE_ENV}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_FIELD_ENCRYPTION_KEY=${DJANGO_FIELD_ENCRYPTION_KEY}
      - DJANGO_API_URL=${DJANGO_API_URL}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SECURE_SSL_REDIRECT=${DJANGO_SECURE_SSL_REDIRECT}
      - DJANGO_SESSION_COOKIE_SECURE=${DJANGO_SESSION_COOKIE_SECURE}
      - DJANGO_CSRF_COOKIE_SECURE=${DJANGO_CSRF_COOKIE_SECURE}
      - USERS_CACHE=${USERS_CACHE}
      - USERS_REFRESH_MINUTES=${USERS_REFRESH_MINUTES}
      - USERS_STATS_REFRESH_MINUTES=${USERS_STATS_REFRESH_MINUTES}
      - WORKFLOWS_CACHE=${WORKFLOWS_CACHE}
      - WORKFLOWS_REFRESH_MINUTES=${WORKFLOWS_REFRESH_MINUTES}
      - AGENT_KEYS=${AGENT_KEYS}
      - MORE_USERS=${MORE_USERS}
      - SESSIONS_LOGS=${SESSIONS_LOGS}
      - RUNS_TIMEOUT_MULTIPLIER=${RUNS_TIMEOUT_MULTIPLIER}
      - RUNS_LOGS=${RUNS_LOGS}
      - RUNS_REFRESH_SECONDS=${RUNS_REFRESH_SECONDS}
      - RUNS_CLEANUP_MINUTES=${RUNS_CLEANUP_MINUTES}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
      - SQL_NAME=${SQL_NAME}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DB=${SQL_DB}
      - GITHUB_AUTH_URI=${GITHUB_AUTH_URI}
      - GITHUB_REDIRECT_URI=${GITHUB_REDIRECT_URI}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_KEY=${GITHUB_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
      - NO_PREVIEW_THUMBNAIL=${NO_PREVIEW_THUMBNAIL}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "plantit.asgi:application"]
    networks:
      - ngnix_network
      - default
    restart: always
    healthcheck:
      test: curl -f http://localhost:8000/ping/
      interval: 20s
      timeout: 20s
      retries: 2
      start_period: 20s
  celery:
    image: computationalplantscience/plantit
    command: ["celery", "-A", "plantit", "worker", "-B", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler", "--loglevel=info", "-Ofair"]
    volumes:
      - .:/code
    working_dir: /code/plantit
    depends_on:
      - redis
    environment:
      - CYVERSE_REDIRECT_URL=${CYVERSE_REDIRECT_URL}
      - CYVERSE_CLIENT_ID=${CYVERSE_CLIENT_ID}
      - CYVERSE_CLIENT_SECRET=${CYVERSE_CLIENT_SECRET}
      - CYVERSE_TOKEN_REFRESH_MINUTES=${CYVERSE_TOKEN_REFRESH_MINUTES}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_FIELD_ENCRYPTION_KEY=${DJANGO_FIELD_ENCRYPTION_KEY}
      - DJANGO_API_URL=${DJANGO_API_URL}
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=${DJANGO_SECURE_SSL_REDIRECT}
      - DJANGO_SESSION_COOKIE_SECURE=${DJANGO_SESSION_COOKIE_SECURE}
      - DJANGO_CSRF_COOKIE_SECURE=${DJANGO_CSRF_COOKIE_SECURE}
      - CELERY_TEMPLATE_LOCAL_RUN_SCRIPT=${CELERY_TEMPLATE_LOCAL_RUN_SCRIPT}
      - CELERY_TEMPLATE_SLURM_RUN_SCRIPT=${CELERY_TEMPLATE_SLURM_RUN_SCRIPT}
      - USERS_CACHE=${USERS_CACHE}
      - USERS_REFRESH_MINUTES=${USERS_REFRESH_MINUTES}
      - USERS_STATS_REFRESH_MINUTES=${USERS_STATS_REFRESH_MINUTES}
      - WORKFLOWS_CACHE=${WORKFLOWS_CACHE}
      - WORKFLOWS_REFRESH_MINUTES=${WORKFLOWS_REFRESH_MINUTES}
      - AGENT_KEYS=${AGENT_KEYS}
      - MORE_USERS=${MORE_USERS}
      - SESSIONS_LOGS=${SESSIONS_LOGS}
      - RUNS_TIMEOUT_MULTIPLIER=${RUNS_TIMEOUT_MULTIPLIER}
      - RUNS_LOGS=${RUNS_LOGS}
      - RUNS_REFRESH_SECONDS=${RUNS_REFRESH_SECONDS}
      - RUNS_CLEANUP_MINUTES=${RUNS_CLEANUP_MINUTES}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
      - SQL_NAME=${SQL_NAME}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DB=${SQL_DB}
      - GITHUB_AUTH_URI=${GITHUB_AUTH_URI}
      - GITHUB_REDIRECT_URI=${GITHUB_REDIRECT_URI}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_KEY=${GITHUB_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
      - NO_PREVIEW_THUMBNAIL=${NO_PREVIEW_THUMBNAIL}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
    healthcheck:
      test: celery -A plantit status | grep "OK"
      interval: 60s
      timeout: 60s
      retries: 2
      start_period: 20s
    restart: always
  redis:
    image: redis:6
    ports:
      - 6379
    volumes:
      - redisdata:/data
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
  sandbox:
    image: computationalplantscience/plantit-sandbox
    command: ["/usr/sbin/sshd", "-D"]
    working_dir: /opt/plantit-cli
    privileged: true
    restart: always
    volumes:
      - ./opt/plantit-cli/tasks/:/opt/plantit-cli/tasks/
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/ssl/:/opt/plantit/config/ssl/
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/certbot/conf:/etc/letsencrypt/
      - ./config/certbot/www:/var/www/certbot
      - ./plantit/static/:/opt/plantit/static/:ro
      - ./plantit/files/public/:/opt/plantit/public/:ro
    depends_on:
      - plantit
    networks:
      - ngnix_network
    restart: always
  certbot:
    image: certbot/certbot
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt/
      - ./config/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;'"
networks:
  ngnix_network:
    driver: bridge
volumes:
  redisdata: