# Base docker-compose file.
#
# Usage:
#  For Developer mode:
#    docker-compose -f docker-compose.yml -f compose-dev.yml up
#
#  For Production mode:
#    docker-compose -f docker-compose.yml -f compose-production.yml up
#
version: '3.7'

services:
  djangoapp:
    build: ./dockerfiles/djangoapp
    working_dir: /code/django
    volumes:
      - .:/code

  rabbitmq:
    image: rabbitmq:3.7.6-management
    hostname: rabbitmq

  celery:
    build: ./dockerfiles/djangoapp
    volumes:
      - .:/code
    working_dir: /code/django
    depends_on:
      - rabbitmq
    command: celery -A plantit worker --loglevel=info

