name: PROD
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Slack start notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: plantit-dev
          SLACK_ICON: https://raw.githubusercontent.com/Computational-Plant-Science/plantit/master/plantit/front_end/src/assets/logo-favicon.png
          SLACK_MESSAGE: 'Building PROD'
          SLACK_TITLE: PlantIT CI
          SLACK_USERNAME: plantit
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ~/.ssh/id_rsa # ${{ github.workspace }}/../private.key
      - name: Deploy production
        env:
          SSH_HOST: ${{ secrets.PROD_HOST }}
          SSH_PORT: ${{ secrets.PROD_PORT }}
          SSH_USER: ${{ secrets.PROD_USER }}
          SSH_DIRECTORY: ${{ secrets.PROD_DIRECTORY }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          chmod +x scripts/deploy-prod.sh
          chmod +x scripts/deploy-prod-ssh.sh
          bash scripts/deploy-prod-ssh.sh
      - name: Slack success notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: plantit-dev
          SLACK_ICON: https://raw.githubusercontent.com/Computational-Plant-Science/plantit/master/plantit/front_end/src/assets/logo-favicon.png
          SLACK_MESSAGE: 'PROD build succeeded'
          SLACK_TITLE: PlantIT CI
          SLACK_USERNAME: plantit