name: release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack start notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: plantit-dev
          SLACK_ICON: https://raw.githubusercontent.com/Computational-Plant-Science/plantit/master/plantit/front_end/src/assets/logo-favicon.png
          SLACK_MESSAGE: 'Deploying release'
          SLACK_TITLE: PlantIT CI
          SLACK_USERNAME: plantit
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ~/.ssh/id_rsa # ${{ github.workspace }}/../private.key
      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
          HOST: ${{ secrets.PROD_HOST }}
          PORT: ${{ secrets.PROD_PORT }}
          USER: ${{ secrets.PROD_USER }}
          DIRECTORY: ${{ secrets.PROD_DIRECTORY }}
          EMAIL: ${{ secrets.PROD_EMAIL }}
          CONFIG: prod
        run: |
          chmod +x scripts/deploy.sh

          eval "$(ssh-agent -s)" # Start ssh-agent cache
          chmod 600 ~/.ssh/id_rsa # Allow read access to the private key
          ssh-add ~/.ssh/id_rsa # Add the private key to SSH

          echo "Deploying $CONFIG"
          ssh -v -o StrictHostKeyChecking=no -p $PORT "$USER@$SSH_HOST" <<EOF
            cd $DIRECTORY
            chmod +x scripts/deploy.sh
            scripts/deploy.sh $CONFIG $HOST $EMAIL
          EOF
      - name: Slack success notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: plantit-dev
          SLACK_ICON: https://raw.githubusercontent.com/Computational-Plant-Science/plantit/master/plantit/front_end/src/assets/logo-favicon.png
          SLACK_MESSAGE: 'Release succeeded'
          SLACK_TITLE: PlantIT CI
          SLACK_USERNAME: plantit